import './footerModal';
import './inputSearch';
import './modalLogIn';
import './movieModal';
import './refs';
import './renderMovieModal';
import './renderMovies';
// import './renderTrendingFilms';
import './movieModal';
import './trailer';
import './watchedLS';
import './queueLS';