export const refs = {
  moviesOnInputList: document.querySelector('.movie__gallery'),
  inputEl: document.querySelector('.search-form'),
  pagePreloader: document.getElementById('page-preloader'),
  loginModal: document.querySelector('[login-data-modal]'),
  loginForm: document.getElementById('login-form'),
  divLoginEmailError: document.getElementById('loginemail-error-message'),
  divLoginPassError: document.getElementById('loginpassword-error-message'),
  signupModal: document.querySelector('[signup-data-modal]'),
  signupForm: document.getElementById('signup-form'),
  divSignUpError: document.getElementById('signup-error-message'),
  signupBtn: document.querySelector('.signup-modal__button'),
  policyCheckbox: document.querySelector('[name="policy-checkbox"]'),
  signoutModal: document.querySelector('[signout-data-modal]'),
};
